<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ru_RU">
<context>
    <name>KGalleryClient</name>
    <message>
        <source>gallery</source>
        <translation>галерея</translation>
    </message>
    <message>
        <source>shape</source>
        <translation>форма</translation>
    </message>
</context>
<context>
    <name>KxDlgEditGallery</name>
    <message>
        <source>EditGallery</source>
        <translation></translation>
    </message>
    <message>
        <source>From:</source>
        <translation>От:</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Текст</translation>
    </message>
    <message>
        <source>Caption:</source>
        <translation>Надпись:</translation>
    </message>
    <message>
        <source>Label:</source>
        <translation>Метка:</translation>
    </message>
    <message>
        <source>The Most Number Of Caption Is 5.</source>
        <translation>Наибольшее количество записей - 5.</translation>
    </message>
    <message>
        <source>More:</source>
        <translation>Больше:</translation>
    </message>
    <message>
        <source>OK</source>
        <translation></translation>
    </message>
    <message>
        <source>Directory:</source>
        <translation>Каталог:</translation>
    </message>
    <message>
        <source>Notes:</source>
        <translation>Записи:</translation>
    </message>
    <message>
        <source>Less:</source>
        <translation>Меньше:</translation>
    </message>
</context>
<context>
    <name>KxEditGalleryDlg</name>
    <message>
        <source>More</source>
        <translation>Больше</translation>
    </message>
    <message>
        <source>Less</source>
        <translation>Меньше</translation>
    </message>
</context>
<context>
    <name>QApplication</name>
    <message>
        <source>\Kingsoft Office\Desktop.ini name.</source>
        <translation></translation>
    </message>
    <message>
        <source>\Kingsoft Office\AppData\Desktop.ini name.</source>
        <translation></translation>
    </message>
    <message>
        <source>\Kingsoft Office\AppData\My Materials\Desktop.ini name.</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>WPSGalleryClass</name>
    <message>
        <source>WPSGallery</source>
        <translation></translation>
    </message>
</context>
</TS>
